name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        include:
          # Current ubuntu
          - os: ubuntu-20.04
            python-version: "3.7"
          - os: ubuntu-20.04
            python-version: "3.8"
          - os: ubuntu-20.04
            python-version: "3.9"

          # Windows
          - os: windows-latest
            python-version: "3.8"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make ci

      - name: Run linter & unit tests
        run: make
